### ISSUE TITLE
TweenGraphicAlpha doesnt work for animators using Image module

### ISSUE THREAD

**Issue by mchangxe** [jeffreylanters/unity-tweens#15]
**Describe the bug**
For some reason TweenGraphicAlpha doesnt work for image renderers rendering a sprite animation.

**To Reproduce**
1. use sprite animation on Image module, call TweenGraphicAlpha on the gameobject.

**Expected behavior**
the sprite animation should fade in or fade out depending on argument of TweenGraphicAlpha

**Desktop (please complete the following information):**
- Windows Editor, Unity 2018.4.8f1

**Comment by jeffreylanters** [comment]
Hello. Thanks for opening this issue, I'm going to look into this and will try to release a patch update as soon as possible.

**Comment by jeffreylanters** [comment]
There might be a change your Sprite Animation is trying to alter the Sprite Renderer's color. If this is the case, the Sprite Animation and Tween are constantly fighting over the target color. Can you confirm your Sprite Animation only alters the Sprite itself as seen in the image below?

![image](https://user-images.githubusercontent.com/3404617/117652012-efb6ac80-b192-11eb-95ca-416b5ba43608.png)

**Comment by jeffreylanters** [comment]
Closed due to inactivity.
