### ISSUE TITLE
Unable to add package via Package Manager UI or direct edit of manifest.json

### ISSUE THREAD

**Issue by bpeck** [jeffreylanters/unity-tweens#23]
Windows 10, Unity 2020.3.14

When I attempt to add the package using the package manager UI and the github URL I get this error in the Console:

> [Package Manager Window] Unable to add package [https://github.com/jeffreylanters/unity-tweens.git]:
>   The file [C:\projects\redacted\Library\PackageCache\@7ac349b634\package.json] is not valid JSON:
>     Unexpected token "}" (0x7D) in JSON at position 591 while parsing near "...aster/LICENSE.md\",\r\n}\r\n"
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

I get similar parsing error when I add the entry to my manifest.json directly.

Cheers

**Comment by jeffreylanters** [comment]
Hi! Thanks for reposting this problem, I’m sorry for the problem. I’ve committed a hot-fix just now. Could you try to re-install the module or remove the entry from your package-lock in order to update to the latest version?
