### ISSUE TITLE
Rename "definitions.asmdef" assembly definition with name easier to search

### ISSUE THREAD

**Issue by hsandt** [jeffreylanters/unity-tweens#30]
**Is your feature request related to a problem? Please describe.**
When referencing this package's assembly from another assembly, the "definitions" file is hard to search. Intuitively you would type things like "Tween" or "ElRaccoone" in the asset search bar, but because it searches by asset file name, not package nor assembly name, it would not find it.

**Describe the solution you'd like**
Rename "definitions.asmdef" into one of these:
a. "nl.elraccoone.tweens.asmdef" (matches assembly name, rigorous)
b. "Elraccoone Tweens.asmdef" (readable name, just enough to distinguish it from other tweens)
c. "Tweens.asmdef" (matches folder name, but not distinguishable from other tweens - although projects rarely combine two tween systems)

With solutions a. and b., searching :elraccoone" or "tween(s)" will work. With c., only searching "tween(s)" will work.

**Describe alternatives you've considered**
Alternatives are described in a. b. c. already.
The current workaround is to search "definitions" instead, but for new users it's hard to guess, they'd have to open the package folder and check the asmdef file themselves.

**Additional context**
Screenshots

Trying to search with "elrac":

![image](https://user-images.githubusercontent.com/1067772/177829715-d076ce70-f92a-4578-824f-1c9dca9baf00.png)

Searching with "defini":

![image](https://user-images.githubusercontent.com/1067772/177829851-d8f64797-7229-4f3b-aaaf-5a9a37e1c488.png)

Note the assembly name (currently domain-style) on the left side. In other projects, it matches the asmdef file name.

**Comment by jeffreylanters** [comment]
Hi! Thanks. This is actually a good suggestion! I'll push the changes tomorrow!

Happy coding!

**Comment by jeffreylanters** [comment]
I've released version [1.12.1](https://github.com/jeffreylanters/unity-tweens/releases/tag/v1.12.1) which includes the change in the package identifier.
