### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by molleindustria** [jeffreylanters/unity-tweens#41]
After installing via git link I get:

`Library\PackageCache\nl.jeffreylanters.tweens@c4f2322175\Runtime\Core\TweenEngine.cs(6,66): error CS8124: Tuple must contain at least two elements.`

`Library\PackageCache\nl.jeffreylanters.tweens@c4f2322175\Runtime\Core\TweenEngine.cs(6,67): error CS1526: A new expression requires (), [], or {} after type`

Unity 2020.3.24f

**Comment by jeffreylanters** [comment]
Seems like an issue with this specific version of Unity. I'm going to look into it, thanks for reporting an issue!
