### ISSUE TITLE
onFinally and onCancel not invoked 

### ISSUE THREAD

**Issue by Pippepot** [jeffreylanters/unity-tweens#46]
When I create a tween and cancel afterwards with CancelTweens, onFinally and onCancel is not invoked

This is clear from the code
```
public sealed override void Cancel() {
      if (!dontInvokeWhenDestroyed && component == null) {
        onCancel?.Invoke(this);
        onFinally?.Invoke(this);
      }
      isDecommissioned = true;
    }
```

In my case the component is not null so the delegates are never invoked

I think the code should look like this

```
    public sealed override void Cancel() {
      if (dontInvokeWhenDestroyed && component == null) {
	isDecommissioned = true;
	return;
      }
      onCancel?.Invoke(this);
      onFinally?.Invoke(this);
      isDecommissioned = true;
    }
```

**Comment by jeffreylanters** [comment]
Hi @Pippepot, please excuse me - I have completely missed this issue. You're absolutely right, very sharp haha. I'll patch it right away!

I've made some minor changes and ended up with the following changes, which should reproduce the same results as your proposal.

```cs
public sealed override void Cancel() {
  if (!dontInvokeWhenDestroyed || component != null) {
    onCancel?.Invoke(this);
    onFinally?.Invoke(this);
  }
  isDecommissioned = true;
}
```

**Comment by jeffreylanters** [comment]
Released, thank you very much for your contribution!

https://github.com/jeffreylanters/unity-tweens/releases/tag/v3.4.1
